# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f68f6a5d441890e2ed271f24fbeff7acc41b395344785cdf5aa5411eacf004b01c0b19fd9792078c987967236864a68553b598e15e7e5b2877a5297b845ed983

test:
  secret_key_base: 448f4913eb7fa668f06c62a0953019c97a05054ece752e1b55caf69bbb5eadfee2463aaf0f63bd23446dd8c547e16569013343454c60b9bcf0a0ae1eadbbb772

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
